### ISSUE TITLE
'isDevToolsOpen' vs 'isDevtoolsOpen'

### ISSUE THREAD

**Issue by tiptronic** [bramblex/niva#21]
Here's something that took me a while to figure out:

It is `Niva.api.webview.isDevtoolsOpen` <> `Niva.api.webview.isDevToolsOpen` (the latter is from the docs)

This one fails:
```javascript
Niva.api.webview.isDevToolsOpen());
```

This one works:
```javascript
Niva.api.webview.isDevtoolsOpen());
```

**Comment by bramblex** [comment]
done.  [https://github.com/bramblex/niva/commit/1ecf237d81f719fdcfdf205b37f6a94ea870ee81](https://github.com/bramblex/niva/commit/1ecf237d81f719fdcfdf205b37f6a94ea870ee81)

**Comment by tiptronic** [comment]
👍
