### ISSUE TITLE
How to listen to the event of tray:menuClicked

### ISSUE THREAD

**Issue by mosuzi** [bramblex/niva#23]
I got confused about how to listen to the event of `tray.menuClicked`.
I tried `tray.leftClicked`, `tray.rightClicked` and `menu.clicked`. Neither of them works.

When I check the source code, nothing is found, again.

**Comment by bramblex** [comment]
This is a bug, and we will fix it in the next version.

In the crrect scenario, when a button in tray menu is cliced, you wil receive a `menu.clicked` event.

**Comment by mosuzi** [comment]
Thanks. Hope for a better niva.
