### ISSUE TITLE
[question]how to create a desktop app

### ISSUE THREAD

**Issue by wanghaisheng** [bramblex/niva#25]
in the old days,I want to create a BS application for users ,but due to media files like video ,pdf can drive the traffic fee blast, I want     user to download this desktop app and install on their own computer, then he can open the deployed url either in browser or just open the desktop app, also if we can compile it into a mobile app would be much better.

Can i achieve this through niva

**Comment by Ir1s666** [comment]
I'm not sure if I fully understand you correctly: you want a set of code that can be run on both the Web and the Desktop.
My answer: Niva is just a tool for building Desktop apps, you just need to deploy your front-end code (for urls) on your server and use niva to build your Desktop packages. As for building on the mobile side, I think that's what similar tools like React-native do, but not niva

**Comment by wanghaisheng** [comment]
i  See
