### ISSUE TITLE
Is there a built-in prevention to stop users from opening devtools?

### ISSUE THREAD

**Issue by sohaha** [bramblex/niva#33]
Sometimes it may be necessary to use.

**Comment by Ir1s666** [comment]
You can double-click the version information in the lower right corner of niva-devtool to open the devtool provided by webview.Alternatively you can also call niva API (Niva.api.webview.openDevtools) to open devtool.

**Comment by bramblex** [comment]
The devtools for the webview is disabled by default in Niva build target. Yout enable it in `niva.json` file [https://bramblex.github.io/niva/docs/options/window](https://bramblex.github.io/niva/docs/options/window). However if you open project in Niva Devtools, the webview devtools always be enabled.
