### ISSUE TITLE
when runing Niva.api.process.exec("code"),the console out put  "program not found"

### ISSUE THREAD

**Issue by lb091188** [bramblex/niva#41]
System: win10
when runing the code with Niva, I`ll meeting error 😂。
test code: 
```js
async function openCode(){
  let dir = await Niva.api.process.currentDir();
  Niva.api.process.exec("code").then(e => {
    console.log(e)
  }).catch( err => console.error(err))
}
```
log:
```json
[
    4,
    -1,
    "program not found",
    null
]
```

call code in cmd is OK！
![image](https://github.com/bramblex/niva/assets/16659166/dac316b7-eec0-434d-ad16-a1fa16627e8c)

请问下，我这是调用方式有问题吗？如果是我调用方式错了，您那边不忙的话，可以给个参考链接吗？

**Comment by bramblex** [comment]
You can try `Niva.api.process.exec("cmd", ['/c', 'code'], {detached:true})` to open VSCode.

你可以尝试一下使用 `Niva.api.process.exec("cmd", ['/c', 'code'], {detached:true})` 来打开 VSCode 程序。

**Comment by lb091188** [comment]
Thks!

**Comment by lb091188** [comment]
抱歉，使用子进程的时间太少了，导致忘记了，需要使用cmd 来调用code 命令。感谢作者这么晚回复。本来还准备在你的掘金上留个言的😂
