### ISSUE TITLE
当构建目录不能存在时，Niva DevTools 进程会卡主并无法退出

### ISSUE THREAD

**Issue by lb091188** [bramblex/niva#58]
![image](https://github.com/bramblex/niva/assets/16659166/2fd3720e-434b-4201-b21b-400c3923be82)
![image](https://github.com/bramblex/niva/assets/16659166/59326201-eaa4-4727-a98b-974fd36a6139)
这是一个我错误配置引发的问题，我使用的是vue3 来构建应用程序，标准打包目录应该是 dist ，我给配成了 build 所以 Niva 找不到这个路径，但是弹窗不消失，当我用任务栏的关闭按钮时，会弹出如图2的提示，只能通过任务栏退出NivaDevtools

**Comment by Ir1s666** [comment]
这个问题会在0.9.10修复
