### ISSUE TITLE
Niva 可以打包成一个单独的 standalone 吗？

### ISSUE THREAD

**Issue by jcc1997** [bramblex/niva#83]
Niva 可以打包成一个单独的 standalone 吗？
如 windows 下是一个单独 exe
mac 下是一个单独的可执行程序

**Comment by bramblex** [comment]
目前 Niva 只支持打包成单独的可执行文件，在 Windows 下面是一个 exe，在 mac 是一个 .app （虽然是一个目录，但是在 Mac 下的表现是一个点击就能打开的 App）
